version: "3"

services:
  web:
    build: nodejs
    ports:
      - "80:1337"
    command: sh -c "/wait && sails lift"
    environment:
      - WAIT_HOSTS=db:3306
      - WAIT_HOSTS_TIMEOUT=30
      - WAIT_SLEEP_INTERVAL=60
      - WAIT_HOST_CONNECT_TIMEOUT=30
 
  db:
    image: mariadb:latest
    ports:
      - 3306
    volumes:
      - ./db/sql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=maria
      - MYSQL_PASSWORD=pass
    
